// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using odata_poc.DbContexts;

namespace odata_poc.Migrations
{
    [DbContext(typeof(FnmaSystemDbContext))]
    [Migration("20210829180806_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("odata_poc.Entities.FnmaSystem", b =>
                {
                    b.Property<int>("FnmaSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OwnerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OwnerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("FnmaSystemId");

                    b.ToTable("Systems");

                    b.HasData(
                        new
                        {
                            FnmaSystemId = 1,
                            DateCreated = new DateTimeOffset(new DateTime(2021, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            OwnerFirstName = "bill",
                            OwnerLastName = "Mclearn"
                        },
                        new
                        {
                            FnmaSystemId = 2,
                            DateCreated = new DateTimeOffset(new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            OwnerFirstName = "jill",
                            OwnerLastName = "Smith"
                        },
                        new
                        {
                            FnmaSystemId = 3,
                            DateCreated = new DateTimeOffset(new DateTime(2001, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            OwnerFirstName = "Jose",
                            OwnerLastName = "Mcdonald"
                        },
                        new
                        {
                            FnmaSystemId = 4,
                            DateCreated = new DateTimeOffset(new DateTime(2016, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            OwnerFirstName = "Tae",
                            OwnerLastName = "Richards"
                        },
                        new
                        {
                            FnmaSystemId = 5,
                            DateCreated = new DateTimeOffset(new DateTime(2005, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, -7, 0, 0, 0)),
                            OwnerFirstName = "Ryan",
                            OwnerLastName = "Lia"
                        });
                });

            modelBuilder.Entity("odata_poc.Entities.SystemInterface", b =>
                {
                    b.Property<int>("SystemInterfaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FnmaSystemId")
                        .HasColumnType("int");

                    b.Property<string>("InterfaceName")
                        .IsRequired()
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)");

                    b.HasKey("SystemInterfaceId");

                    b.HasIndex("FnmaSystemId");

                    b.ToTable("Interface");

                    b.HasData(
                        new
                        {
                            SystemInterfaceId = 1,
                            FnmaSystemId = 1,
                            InterfaceName = "Credit Checker"
                        },
                        new
                        {
                            SystemInterfaceId = 2,
                            FnmaSystemId = 2,
                            InterfaceName = "CFOC Center"
                        },
                        new
                        {
                            SystemInterfaceId = 3,
                            FnmaSystemId = 3,
                            InterfaceName = "Discolsure Processor"
                        },
                        new
                        {
                            SystemInterfaceId = 4,
                            FnmaSystemId = 4,
                            InterfaceName = "DUC Loan Processor"
                        },
                        new
                        {
                            SystemInterfaceId = 5,
                            FnmaSystemId = 5,
                            InterfaceName = "Aquisition Monitor"
                        });
                });

            modelBuilder.Entity("odata_poc.Entities.SystemInterface", b =>
                {
                    b.HasOne("odata_poc.Entities.FnmaSystem", "FnmaSystem")
                        .WithMany("SystemInterface")
                        .HasForeignKey("FnmaSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FnmaSystem");
                });

            modelBuilder.Entity("odata_poc.Entities.FnmaSystem", b =>
                {
                    b.Navigation("SystemInterface");
                });
#pragma warning restore 612, 618
        }
    }
}
